### ISSUE TITLE
RpcException when having parallel requests

### ISSUE THREAD

**Issue by LoW0lf** [Azure-Samples/hello-spring-function-azure#25] opened 2021-01-21 08:31 UTC
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
* Deploy spring function sample app to Azure Function (Consumption Plan) 
* Simulate peak with 180 parallel users sending GET requests to "hello" function (e.g. with JMeter)
* Wait for getting HTTP 500 Exceptions

### Any log messages given by the failure
Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcException:
```

Exception while executing function: Functions.hello Result: Failure
Exception: NoSuchElementException: 
Stack: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.microsoft.azure.functions.worker.broker.JavaMethodInvokeInfo.invoke(JavaMethodInvokeInfo.java:22)
	at com.microsoft.azure.functions.worker.broker.EnhancedJavaMethodExecutorImpl.execute(EnhancedJavaMethodExecutorImpl.java:55)
	at com.microsoft.azure.functions.worker.broker.JavaFunctionBroker.invokeMethod(JavaFunctionBroker.java:57)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:33)
	at com.microsoft.azure.functions.worker.handler.InvocationRequestHandler.execute(InvocationRequestHandler.java:10)
	at com.microsoft.azure.functions.worker.handler.MessageHandler.handle(MessageHandler.java:45)
	at com.microsoft.azure.functions.worker.JavaWorkerClient$StreamingMessagePeer.lambda$onNext$0(JavaWorkerClient.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: java.util.NoSuchElementException
	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:101)
	at com.example.HelloHandler.execute(HelloHandler.java:28)
	... 15 more
Caused by: java.lang.IllegalStateException: java.util.NoSuchElementException
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:327)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:281)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:239)
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:82)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:63)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:62)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:362)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
	at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:118)
	at org.springframework.cloud.function.adapter.azure.AzureSpringBootRequestHandler.handleRequest(AzureSpringBootRequestHandler.java:82)
	... 16 more
Caused by: java.util.NoSuchElementException
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at ch.qos.logback.classic.LoggerContext.fireOnReset(LoggerContext.java:323)
	at ch.qos.logback.classic.LoggerContext.reset(LoggerContext.java:226)
	at ch.qos.logback.classic.LoggerContext.stop(LoggerContext.java:348)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.stopAndReset(LogbackLoggingSystem.java:196)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadDefaults(LogbackLoggingSystem.java:144)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:83)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:312)
	... 33 more
```

### Expected/desired behavior
Azure function on consumption plan can scale out seamlessly (without exceptions) as parallel requests increase. 

### Configuration Function App
FUNCTIONS_EXTENSION_VERSION: ~3
FUNCTIONS_WORKER_RUNTIME: java

**Comment by jdubois** [comment] 2021-01-21 10:08
Thanks, but as this is just a sample project, and that your bug comes from https://github.com/spring-cloud/spring-cloud-function , I suggest that you post the bug report there (and that I help you there, of course!).

Reading the `AzureSpringBootRequestHandler` code, it seems to me you can indeed have 2 calls at the same time on the handler, and so you could use a Spring context that is not fully initialized.

On https://github.com/spring-cloud/spring-cloud-function/pull/428/files there was a synchronized block, which has disappeared.
And it's not exactly the same bug (they are using two functions), but https://github.com/spring-cloud/spring-cloud-function/issues/437 also seems related to your issue.

Let's discuss this on a ticket on https://github.com/spring-cloud/spring-cloud-function but can you detail more when you get the error? Do you have this for all requests, or is that pretty rare and only at the beginning? I'm trying to understand better if that's an initialization issue.

**Comment by LoW0lf** [comment] 2021-01-21 12:16
Thank you very much for analysing the issue and providing the further information.

We will have a further look into the existing issues and create a ticket in the spring cloud function repo if we can add additional information there. 

Here you can see the distribution of the faulty requests over the entire test period. Of approx. 840k requests we had about 1.43k RpcExceptions - most of them very close together:
![image](https://user-images.githubusercontent.com/8620039/105350020-d2150580-5bea-11eb-865e-2c7725556fe1.png)

**Comment by jdubois** [comment] 2021-01-21 12:36
Thank you so much!

- Indeed that seems to show the issue is during initialization
- Be careful with that test: Azure Functions scales automatically, so at some point you will have more instances, and so the issue might arrive again at this time. There's no official metrics there, but with what you do this is probably going to kick some new instances at some point.
- I'd be interested to discuss billing with you: you are normally billed only for the CPU/memory you use, and it seems that here you have up to 400 concurrent requests, so typically you should pay a lot less than what you would pay for 840k requests. I'm guessing your bill will be 100x less than with a competitor who doesn't accept multi-threading (and in exchange you wouldn't have our current issue, of course!!!)
- This JMeter test is very useful -> I'll probably steal your idea and do a similar scenario with Gatling

**Comment by SamuelBucheliZ** [comment] 2021-01-21 12:47
As far as I can tell, this is also related to https://github.com/spring-cloud/spring-cloud-function/issues/526

**Comment by jdubois** [comment] 2021-01-21 16:41
I just added a Gatling test to prove it: https://github.com/Azure-Samples/hello-spring-function-azure/commit/d6c0e08d6a024664a60a11e5d6de58fd88aa0c3f

- Run the application locally: mvn azure-functions:run
- Run the Gatling test: mvn gatling:run

This triggers the issue very easily on my laptop

**Comment by jdubois** [comment] 2021-01-27 17:33
I just migrated this sample to use Spring Webflux instead of Spring Web - this was for other reasons, but it seems that it fixes the issue! At least, I can't reproduce it, and I used to be able to reproduce it very easily.

@LoW0lf could you check out this update, and test again? This would be a great side-effect.

**Comment by jdubois** [comment] 2021-03-15 11:50
Closing as this looks fixed.

**Closed by jdubois** 2021-03-15 11:50 UTC
