### ISSUE TITLE
Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(Object)" because "function" is null

### ISSUE THREAD

**Issue by decifris** [Azure-Samples/hello-spring-function-azure#32] opened 2021-08-28 13:40 UTC
I'm getting this error:

`Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(Object)" because "function" is null`

I didn't modify anything, just ran the code from the repo
Console log: https://pastebin.com/W2EbkDV4

[Video](https://imgur.com/KnAvNfH)

**Comment by jdubois** [comment] 2021-08-30 07:53
The video is a bit blurry, but from my understanding you're not deploying to Azure, but running the code on your laptop, is this correct?
If that's running on your machine, it can be caused by different configuration issues, typically how Azure Functions is installed. How do you run your application, are you using "mvn azure-functions:run"? And are you on a Mac? How did you install Azure Functions, did you use Homebrew?

**Comment by decifris** [comment] 2021-08-31 14:29
I use [Azure Toolkit for Intellij](https://plugins.jetbrains.com/plugin/8053-azure-toolkit-for-intellij), then I just run the function from there

![function](https://user-images.githubusercontent.com/87373648/131521043-58cff636-a417-42a7-a6c5-51d19afbe276.png)

**Comment by jdubois** [comment] 2021-08-31 14:34
Oh I have no idea if that works. Did you try `./mvnw azure-functions:run` like in the quickstart?

**Comment by jdubois** [comment] 2021-08-31 14:41
I just tested and I have the same issue - I'm not sure this plugin correctly supports Java. Anyway that's a bug in the plugin, I'll contact the team about this.

Closing this as it's a bug in the Intellij plugin, not in this repo.

**Closed by jdubois** 2021-08-31 14:41 UTC
